name = "idlewild-portfolio"
main = "index.js"
compatibility_date = "2024-12-01"

# Environment variables (optional)
[env.production]
name = "idlewild-portfolio"

[env.staging]
name = "idlewild-portfolio-staging"